# Site settings
title: Puru-Logs🫶
email: purusharth19malik@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I write about any rabbit hole that I go into twice a month.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: https://www.linkedin.com/in/purusharth-malik-33a31616b/
github_username: purusharthmalik

# Build settings
theme: minima
markdown: kramdown  # Enables Markdown rendering using Kramdown
highlighter: rouge  # Optional: Enables syntax highlighting for code blocks

plugins:
  - jekyll-feed
  - jekyll-paginate  # Optional: Adds pagination support
  - jekyll-seo-tag  # Optional: Improves SEO meta tags

# Kramdown settings (optional, for fine-tuned Markdown rendering)
kramdown:
  input: GFM  # Enables GitHub Flavored Markdown (GFM) for better compatibility
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6  # Enables Table of Contents (TOC) from headings